export const IPC = {
  PTY_CREATE: 'pty:create',
  PTY_DATA: 'pty:data',
  PTY_WRITE: 'pty:write',
  PTY_RESIZE: 'pty:resize',
  PTY_DESTROY: 'pty:destroy',
  PTY_GET_PROCESS: 'pty:get-process',
  PTY_EXIT: 'pty:exit',
  PTY_TITLE: 'pty:title',

  HISTORY_GET: 'history:get',
  HISTORY_ADD: 'history:add',
  HISTORY_CLEAR: 'history:clear',

  SETTINGS_GET: 'settings:get',
  SETTINGS_SET: 'settings:set',

  APP_SETTINGS: 'app:settings',
  APP_NEW_TAB: 'app:new-tab',
  APP_CLOSE_TAB: 'app:close-tab',
  APP_NEXT_TAB: 'app:next-tab',
  APP_PREV_TAB: 'app:prev-tab',
  APP_SWITCH_TAB: 'app:switch-tab',
  APP_CLEAR: 'app:clear',
  APP_SEARCH: 'app:search',
  APP_FONT_SIZE_UP: 'app:font-size-up',
  APP_FONT_SIZE_DOWN: 'app:font-size-down',
  APP_SPLIT_VERTICAL: 'app:split-vertical',
  APP_SPLIT_HORIZONTAL: 'app:split-horizontal',
  APP_FOCUS_PANE_UP: 'app:focus-pane-up',
  APP_FOCUS_PANE_DOWN: 'app:focus-pane-down',
  APP_FOCUS_PANE_LEFT: 'app:focus-pane-left',
  APP_FOCUS_PANE_RIGHT: 'app:focus-pane-right',

  SESSION_GET: 'session:get',
  SESSION_SET: 'session:set',
  PTY_GET_CWD: 'pty:get-cwd',

  APP_OPEN_IN_EDITOR: 'app:open-in-editor',
  APP_SAVE_TERMINAL: 'app:save-terminal',
  APP_BROADCAST_INPUT: 'app:broadcast-input',
  APP_NOTIFY: 'app:notify',

  APP_SPLIT_ZOOM: 'app:split-zoom',
  APP_UNDO_CLOSE: 'app:undo-close',
  APP_COMMAND_PALETTE: 'app:command-palette',
  APP_PROMPT_JUMP_UP: 'app:prompt-jump-up',
  APP_PROMPT_JUMP_DOWN: 'app:prompt-jump-down',
  APP_QUICK_TERMINAL: 'app:quick-terminal',
  APP_SET_OPACITY: 'app:set-opacity',
  APP_SAVE_TERMINAL_MENU: 'app:save-terminal-menu',
  APP_SWITCH_TAB_BY_ID: 'app:switch-tab-by-id',
  APP_OPEN_EXTERNAL: 'app:open-external',
  WINDOW_MOVE_BY: 'window:move-by',

  DIAGNOSTICS_SAVE_SNAPSHOT: 'diagnostics:save-snapshot',
} as const;

export const DEFAULTS = {
  SHELL: '/bin/zsh',
  COLS: 80,
  ROWS: 24,
  FONT_SIZE: 14,
  FONT_FAMILY: "'SF Mono', 'Menlo', 'Monaco', 'Courier New', monospace",
  SCROLLBACK: 10000,
  HISTORY_MAX: 10000,
  WRITE_COALESCE_MS: 4,
  FONT_SIZE_MIN: 8,
  FONT_SIZE_MAX: 72,
  NOTIFICATION_SOUND: true,
  NOTIFICATION_SOUND_TYPE: 'chime' as const,
  STARTUP_COMMAND: '' as const,
  MAX_PANES_PER_TAB: 5,
} as const;

export const PATTON_QUOTES = [
  'A good plan violently executed now is better than a perfect plan executed next week.',
  "If everybody is thinking alike, then somebody isn't thinking.",
  'It is foolish and wrong to mourn the men who died. Rather, we should thank God that such men lived.',
  "Don't tell people how to do things, tell them what to do and let them surprise you with their results.",
  'Better to fight for something than live for nothing.',
  "I don't measure a man's success by how high he climbs but how high he bounces when he hits bottom.",
  'Anyone in any walk of life who is content with mediocrity is untrue to himself and to American tradition.',
  'Do your duty as you see it, and damn the consequences.',
  'A man must know his destiny\u2026 if he does not recognize it, then he is lost. By this I mean, once, twice, or at the very most, three times, fate will reach out and tap a man on the shoulder\u2026 if he has the imagination, he will turn around and fate will point out to him what fork in the road he should take, if he has the guts, he will take it.',
  'Wars may be fought with weapons, but they are won by men. It is the spirit of men who follow and of the man who leads that gains the victory.',
  'When in doubt, ATTACK!',
  'Accept the challenges so that you can feel the exhilaration of victory.',
  'A pint of sweat will save a gallon of blood.',
  "Do not make excuses, whether it's your fault or not.",
  "I don't fear failure. I only fear the slowing up of the engine inside of me which is saying, 'Keep going, someone must be on top, why not you?'",
  'Take calculated risks. That is quite different from being rash.',
  'Nobody ever defended anything successfully, there is only attack and attack and attack some more.',
  'An Army is a team. It lives, sleeps, eats and fights as a team. This individual heroic stuff is pure horse shit.',
  'Always do more than is required of you.',
];

